In [1]:
import numpy as np

# Create a 1-D NumPy array with 5 elements
arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)

# a) Addition of 2 to all elements
print("After adding 2:", arr + 2)

# b) Multiply 3 with all elements
print("After multiplying by 3:", arr * 3)

# c) Divide every element by 2
print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

# Reverse the array
reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [3]:
import numpy as np

# Array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Find frequencies
values, counts = np.unique(x, return_counts=True)

# Find maximum frequency
max_count = counts.max()

# Find all most frequent values
most_frequent_values = values[counts == max_count]

print("Array x:", x)
print("Most frequent value(s):", most_frequent_values)
print("Maximum frequency:", max_count)

for value in most_frequent_values:
    indices = np.where(x == value)[0]
    print("Value", value, "occurs at indices:", indices)


# Array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_count = counts.max()

most_frequent_values = values[counts == max_count]

print("\nArray y:", y)
print("Most frequent value(s):", most_frequent_values)
print("Maximum frequency:", max_count)

for value in most_frequent_values:
    indices = np.where(y == value)[0]
    print("Value", value, "occurs at indices:", indices)

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value(s): [1]
Maximum frequency: 5
Value 1 occurs at indices: [0 5 7 8 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value(s): [1 3]
Maximum frequency: 3
Value 1 occurs at indices: [0 1 2]
Value 3 occurs at indices: [4 8 9]


In [4]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# a) Access 1st row, 2nd column
# Python uses 0-based indexing: row 0, column 1
print("1st row, 2nd column:", arr[0, 1])

# b) Access 3rd row, 1st column
# Python: row 2, column 0
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [ ]:
import numpy as np

# Create 1-D array named Akansh
Akansh = np.linspace(10, 100, 25)

print("Array:")
print(Akansh)

# Dimensions
print("\nDimensions:", Akansh.ndim)

# Shape
print("Shape:", Akansh.shape)

# Total number of elements
print("Total elements:", Akansh.size)

# Data type
print("Data type:", Akansh.dtype)

# Total number of bytes
print("Total bytes consumed:", Akansh.nbytes)

# Transpose using reshape()
Akansh_transpose = Akansh.reshape(1, 25)

print("\nTranspose using reshape():")
print(Akansh_transpose)

print("Shape after reshape:", Akansh_transpose.shape)

# Transpose using T attribute
Akansh_T = Akansh.T

print("\nUsing T attribute:")
print(Akansh_T)

print("Shape using T:", Akansh_T.shape)

print("\nCan we do the same with T attribute?")
print("For a 1-D NumPy array, T does not change its shape.")
print("Therefore, reshape() is needed to convert it into a row/column 2-D array.")

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transpose using reshape():
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Shape after reshape: (1, 25)

Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape using T: (25,)

Can we do the same with T attribute?
For a 1-D NumPy array, T does not change its shape.
Therefore, reshape() is needed to convert it into a row/column 2-D array.


In [ ]:
import numpy as np

# Create 3 x 4 array
ucs420_Akansh = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original array:")
print(ucs420_Akansh)

# Mean
print("\nMean:", np.mean(ucs420_Akansh))

# Median
print("Median:", np.median(ucs420_Akansh))

# Maximum
print("Maximum:", np.max(ucs420_Akansh))

# Minimum
print("Minimum:", np.min(ucs420_Akansh))

# Unique elements
print("Unique elements:", np.unique(ucs420_Akansh))

# Reshape to 4 rows and 3 columns
reshaped_ucs420_Akansh = ucs420_Akansh.reshape(4, 3)

print("\nReshaped array (4 x 3):")
print(reshaped_ucs420_Akansh)

# Resize to 2 rows and 3 columns
resized_ucs420_Akansh = np.resize(ucs420_Akansh, (2, 3))

print("\nResized array (2 x 3):")
print(resized_ucs420_Akansh)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 x 3):
[[10 20 30]
 [40 50 60]]
