In [1]:
import numpy as np

# Sensor temperature readings
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a) Add 2°C to every reading using vectorization
corrected_temperature = temperature + 2

print("Original temperature readings:")
print(temperature)

print("\nCorrected temperature readings:")
print(corrected_temperature)


# b) Convert Celsius to Fahrenheit
# Formula: F = (9/5)C + 32
fahrenheit = (9 / 5) * corrected_temperature + 32

print("\nTemperature in Fahrenheit:")
print(fahrenheit)


# c) Identify all readings greater than 32°C using Boolean indexing
readings_greater_32 = corrected_temperature[corrected_temperature > 32]

print("\nReadings greater than 32°C:")
print(readings_greater_32)


# d) Count how many readings exceed 32°C
count_greater_32 = np.sum(corrected_temperature > 32)

print("\nNumber of readings greater than 32°C:")
print(count_greater_32)


# e) Explanation
print("\nExplanation:")
print("Vectorization allows NumPy to perform an operation on the entire array")
print("at once instead of explicitly processing each element using a for loop.")
print("Boolean indexing creates a Boolean condition for every element and")
print("directly selects the elements that satisfy the condition.")
print("This makes numerical data processing shorter, faster, and more efficient.")

Original temperature readings:
[25 28 31 35 38 27 33 40]

Corrected temperature readings:
[27 30 33 37 40 29 35 42]

Temperature in Fahrenheit:
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]

Readings greater than 32°C:
[33 37 40 35 42]

Number of readings greater than 32°C:
5

Explanation:
Vectorization allows NumPy to perform an operation on the entire array
at once instead of explicitly processing each element using a for loop.
Boolean indexing creates a Boolean condition for every element and
directly selects the elements that satisfy the condition.
This makes numerical data processing shorter, faster, and more efficient.


In [2]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Steps matrix:")
print(steps)


# a) Calculate total steps recorded
total_steps = np.sum(steps)

print("\na) Total steps:", total_steps)


# b) Calculate mean number of steps
mean_steps = np.mean(steps)

print("b) Mean number of steps:", mean_steps)


# c) Find maximum and minimum values
maximum_steps = np.max(steps)
minimum_steps = np.min(steps)

print("c) Maximum steps:", maximum_steps)
print("   Minimum steps:", minimum_steps)


# d) Total steps for each day using axis=0
total_each_day = np.sum(steps, axis=0)

print("d) Total steps for each day:", total_each_day)


# e) Total steps for each user using axis=1
total_each_user = np.sum(steps, axis=1)

print("e) Total steps for each user:", total_each_user)


# f) Find user/day position containing maximum number of steps
max_position = np.unravel_index(np.argmax(steps), steps.shape)

print("f) Position of maximum number of steps:", max_position)
print("   Maximum value:", steps[max_position])
print("   User number:", max_position[0] + 1)
print("   Day number:", max_position[1] + 1)

Steps matrix:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]

a) Total steps: 84200
b) Mean number of steps: 7016.666666666667
c) Maximum steps: 9500
   Minimum steps: 4500
d) Total steps for each day: [26500 27300 30400]
e) Total steps for each user: [18300 24500 14400 27000]
f) Position of maximum number of steps: (np.int64(3), np.int64(2))
   Maximum value: 9500
   User number: 4
   Day number: 3


In [3]:
import numpy as np

# a) Create the original array
original = np.array([1, 2, 3, 4, 5, 6])

print("Original array:")
print(original)


# b) Create a slice from index 1 to 4
# This includes indices 1, 2, and 3
subset = original[1:4]

print("\nSubset:")
print(subset)


# c) Modify the first element of subset to 999
subset[0] = 999

print("\nAfter modifying subset:")
print("Original:", original)
print("Subset:", subset)

print("\nThe original array is also affected because a normal NumPy slice")
print("creates a view of the original array rather than an independent copy.")


# d) Create another slice using .copy()
copied_array = original[1:4].copy()

# Modify its first element
copied_array[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied array:", copied_array)

print("\nThe original array is not affected because .copy() creates")
print("an independent copy of the data.")

Original array:
[1 2 3 4 5 6]

Subset:
[2 3 4]

After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4]

The original array is also affected because a normal NumPy slice
creates a view of the original array rather than an independent copy.

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4]

The original array is not affected because .copy() creates
an independent copy of the data.


In [4]:
import numpy as np

# e) Create numbers from 1 to 12 and reshape into 3 x 4
matrix = np.arange(1, 13).reshape(3, 4)

print("3 x 4 matrix:")
print(matrix)


# f) Extract required elements

# First row
first_row = matrix[0, :]

# Last row
last_row = matrix[-1, :]

# Second column
second_column = matrix[:, 1]

# Elements from rows 1-2 and columns 2-3
# Using Python's 0-based indexing:
# rows 1-2 -> indices 1 and 2
# columns 2-3 -> indices 2 and 3
selected_elements = matrix[1:3, 2:4]


print("\nFirst row:")
print(first_row)

print("\nLast row:")
print(last_row)

print("\nSecond column:")
print(second_column)

print("\nElements from rows 1-2 and columns 2-3:")
print(selected_elements)

3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row:
[1 2 3 4]

Last row:
[ 9 10 11 12]

Second column:
[ 2  6 10]

Elements from rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]


In [5]:
import numpy as np

# Create the 3 x 4 matrix again
matrix = np.arange(1, 13).reshape(3, 4)

# g) Flatten using flatten() and ravel()
flattened_array = matrix.flatten()
ravel_array = matrix.ravel()

print("Original matrix:")
print(matrix)

print("\nUsing flatten():")
print(flattened_array)

print("\nUsing ravel():")
print(ravel_array)


# h) Modify an element in ravel()
ravel_array[0] = 999

print("\nAfter modifying ravel()[0] to 999:")
print("Ravel array:")
print(ravel_array)

print("Original matrix:")
print(matrix)

print("\nThe original matrix is affected because ravel() normally")
print("returns a view of the original array when possible.")


# i) Modify an element in flatten()
flattened_array[1] = 500

print("\nAfter modifying flatten()[1] to 500:")
print("Flattened array:")
print(flattened_array)

print("Original matrix:")
print(matrix)

print("\nThe original matrix is NOT affected because flatten()")
print("returns a copy of the array.")

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Using flatten():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Using ravel():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel()[0] to 999:
Ravel array:
[999   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

The original matrix is affected because ravel() normally
returns a view of the original array when possible.

After modifying flatten()[1] to 500:
Flattened array:
[  1 500   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

The original matrix is NOT affected because flatten()
returns a copy of the array.


In [6]:
import numpy as np

# Original 3 x 4 matrix
matrix = np.arange(1, 13).reshape(3, 4)

print("Original matrix:")
print(matrix)

# Shape
print("\nShape:", matrix.shape)

# Number of dimensions
print("Dimensions (ndim):", matrix.ndim)

# Total number of elements
print("Size (total elements):", matrix.size)

# Data type
print("Data type:", matrix.dtype)

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Dimensions (ndim): 2
Size (total elements): 12
Data type: int64


In [7]:
import numpy as np

# Feature matrix X
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

# Target values
y = np.array([40, 65, 30, 85])


# a) Display shape and dimensions of X
print("X:")
print(X)

print("\nShape of X:", X.shape)
print("Dimensions of X:", X.ndim)


# b) Calculate X.T
X_transpose = X.T

print("\nX.T:")
print(X_transpose)

print("\nExplanation:")
print("X has one row for each user and one column for each feature.")
print("Therefore, X.T changes the arrangement so that each row")
print("corresponds to one feature and each column corresponds to a user.")


# c) Calculate X.T @ X
XTX = X.T @ X

print("\nX.T @ X:")
print(XTX)

X:
[[ 6 70  3]
 [ 5 50  6]
 [ 8 80  2]
 [ 4 30  8]]

Shape of X: (4, 3)
Dimensions of X: 2

X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

Explanation:
X has one row for each user and one column for each feature.
Therefore, X.T changes the arrangement so that each row
corresponds to one feature and each column corresponds to a user.

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [8]:
import numpy as np

# Feature matrix
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

# Target values
y = np.array([40, 65, 30, 85])


# Calculate X.T @ X
XTX = X.T @ X

print("X.T @ X:")
print(XTX)


# d) Calculate inverse of X.T @ X
XTX_inverse = np.linalg.inv(XTX)

print("\nInverse of X.T @ X:")
print(XTX_inverse)


# e) Ordinary Least Squares equation:
# beta = (X.T @ X)^(-1) @ X.T @ y

beta = XTX_inverse @ X.T @ y

print("\nOLS coefficients (beta):")
print(beta)


# f) Explain coefficients
print("\nExplanation of coefficients:")
print("Coefficient 1 corresponds to Sleep Hours.")
print("Coefficient 2 corresponds to Activity Level.")
print("Coefficient 3 corresponds to Stress Level.")
print("Each coefficient represents the estimated change in the")
print("assistance score associated with a one-unit change in that")
print("feature, while the other features are held constant.")


# g) Predict assistance score for new user
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\nNew user:")
print(new_user)

print("\nPredicted assistance score:")
print(predicted_score)

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS coefficients (beta):
[-0.15921454  0.14083853 10.06302242]

Explanation of coefficients:
Coefficient 1 corresponds to Sleep Hours.
Coefficient 2 corresponds to Activity Level.
Coefficient 3 corresponds to Stress Level.
Each coefficient represents the estimated change in the
assistance score associated with a one-unit change in that
feature, while the other features are held constant.

New user:
[ 5 40  7]

Predicted assistance score:
75.27862544779117
